apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ui-plugin-logging.yaml
- ui-plugin-monitoring.yaml
- ui-plugin-distributed-tracing.yaml
- ui-plugin-troubleshooting-panel.yaml
- ui-plugin-dashboards.yaml
