apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-observability-operator.yaml
- loki-operator.yaml
- tempo-operator.yaml
- opentelemetry-operator.yaml
- cluster-logging-operator.yaml
