quarkus.application.name=order-service
quarkus.http.port=8080

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.rest-client.catalog-service.url=http://catalog-service:8080
